name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: target/release/architect
            asset_name: architect-linux
          - os: windows-latest
            artifact_name: target/release/architect.exe
            asset_name: architect-windows.exe
          - os: macos-latest
            artifact_name: target/release/architect
            asset_name: architect-macos

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --bin architect --locked

      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
